# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pyQtGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1700, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1700, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(236, 236, 242);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Interactive_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.Interactive_widget.setGeometry(QtCore.QRect(20, 80, 401, 771))
        self.Interactive_widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Interactive_widget.setStyleSheet("QWidget#DB_tab{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QWidget#Cfg_tab{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QWidget#Info_tab{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"#Result_frame {\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"}\n"
"\n"
"#Result_label {\n"
"    background-color: rgb(236, 236, 242);\n"
"    border-radius: 20px;\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#Total_num {\n"
"    background-color:rgb(0, 70, 255);\n"
"}\n"
"\n"
"#Passed_num {\n"
"    background-color:rgb(157, 201, 91);\n"
"}\n"
"\n"
"#Failed_num {\n"
"    background-color:rgb(255, 0, 92);\n"
"}\n"
"\n"
"#Start_btn {\n"
"    border-radius: 20px;\n"
"    background-color:rgb(157, 201, 91);\n"
"}\n"
"\n"
"#Start_btn:hover {\n"
"    background-color:rgb(85, 170, 127);\n"
"}\n"
"\n"
"#Stop_btn {\n"
"    border-radius: 20px;\n"
"    background-color:rgb(255, 0, 92);\n"
"}\n"
"\n"
"#Stop_btn:hover {\n"
"    background-color:rgb(255, 0, 0);\n"
"}\n"
"\n"
"#Set_btn {\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0, 70, 255);\n"
"}\n"
"\n"
"#Set_btn:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    selection-background-color:rgb(129, 192, 190);\n"
"}\n"
"\n"
"QSlider {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSlider::handle {\n"
"    background-color: rgb(129, 192, 190);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-color: rgb(129, 192, 190);\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(129, 192, 190);\n"
"    border-radius: 2px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QCheckBox::indicator::checked {\n"
"    background-color: rgb(129, 192, 190);\n"
"}\n"
"\n"
"QSpinBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"    border-radius: 5px;\n"
"    font-size: 12;\n"
"}\n"
"\n"
"#Port_btn {\n"
"    border-radius: 20px;\n"
"    background-color:rgb(128, 191, 189);\n"
"}\n"
"\n"
"#Port_btn:hover {\n"
"    background-color:rgb(85, 170, 127);\n"
"}\n"
"\n"
"#Cam_btn {\n"
"    border-radius: 20px;\n"
"    background-color:rgb(128, 191, 189);\n"
"}\n"
"\n"
"#Cam_btn:hover {\n"
"    background-color:rgb(85, 170, 127);\n"
"}")
        self.Interactive_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Interactive_widget.setLineWidth(0)
        self.Interactive_widget.setObjectName("Interactive_widget")
        self.DB_tab = QtWidgets.QWidget()
        self.DB_tab.setObjectName("DB_tab")
        self.DB_indicator = QtWidgets.QFrame(self.DB_tab)
        self.DB_indicator.setGeometry(QtCore.QRect(20, 10, 51, 3))
        self.DB_indicator.setStyleSheet("background:rgb(129, 192, 190);")
        self.DB_indicator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DB_indicator.setLineWidth(0)
        self.DB_indicator.setMidLineWidth(0)
        self.DB_indicator.setFrameShape(QtWidgets.QFrame.HLine)
        self.DB_indicator.setObjectName("DB_indicator")
        self.Result_frame = QtWidgets.QLabel(self.DB_tab)
        self.Result_frame.setGeometry(QtCore.QRect(50, 30, 300, 300))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.Result_frame.setFont(font)
        self.Result_frame.setStyleSheet("")
        self.Result_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.Result_frame.setObjectName("Result_frame")
        self.Result_label = QtWidgets.QLabel(self.DB_tab)
        self.Result_label.setGeometry(QtCore.QRect(130, 343, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.Result_label.setFont(font)
        self.Result_label.setStyleSheet("")
        self.Result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Result_label.setObjectName("Result_label")
        self.Total_label = QtWidgets.QLabel(self.DB_tab)
        self.Total_label.setGeometry(QtCore.QRect(40, 420, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Total_label.setFont(font)
        self.Total_label.setObjectName("Total_label")
        self.Total_num = QtWidgets.QLineEdit(self.DB_tab)
        self.Total_num.setGeometry(QtCore.QRect(220, 415, 140, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Total_num.setFont(font)
        self.Total_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Total_num.setReadOnly(True)
        self.Total_num.setObjectName("Total_num")
        self.Passed_label = QtWidgets.QLabel(self.DB_tab)
        self.Passed_label.setGeometry(QtCore.QRect(40, 477, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Passed_label.setFont(font)
        self.Passed_label.setObjectName("Passed_label")
        self.Failed_label = QtWidgets.QLabel(self.DB_tab)
        self.Failed_label.setGeometry(QtCore.QRect(40, 533, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Failed_label.setFont(font)
        self.Failed_label.setObjectName("Failed_label")
        self.Passed_num = QtWidgets.QLineEdit(self.DB_tab)
        self.Passed_num.setGeometry(QtCore.QRect(220, 471, 140, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Passed_num.setFont(font)
        self.Passed_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Passed_num.setReadOnly(True)
        self.Passed_num.setObjectName("Passed_num")
        self.Failed_num = QtWidgets.QLineEdit(self.DB_tab)
        self.Failed_num.setGeometry(QtCore.QRect(220, 528, 140, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Failed_num.setFont(font)
        self.Failed_num.setAlignment(QtCore.Qt.AlignCenter)
        self.Failed_num.setReadOnly(True)
        self.Failed_num.setObjectName("Failed_num")
        self.Start_btn = QtWidgets.QPushButton(self.DB_tab)
        self.Start_btn.setGeometry(QtCore.QRect(40, 680, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        self.Start_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_btn.setIcon(icon1)
        self.Start_btn.setIconSize(QtCore.QSize(40, 40))
        self.Start_btn.setCheckable(True)
        self.Start_btn.setObjectName("Start_btn")
        self.Stop_btn = QtWidgets.QPushButton(self.DB_tab)
        self.Stop_btn.setGeometry(QtCore.QRect(220, 680, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        self.Stop_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop_btn.setIcon(icon2)
        self.Stop_btn.setIconSize(QtCore.QSize(40, 40))
        self.Stop_btn.setCheckable(True)
        self.Stop_btn.setObjectName("Stop_btn")
        self.Set_btn = QtWidgets.QPushButton(self.DB_tab)
        self.Set_btn.setGeometry(QtCore.QRect(125, 590, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        self.Set_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\icons/thunderbolt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Set_btn.setIcon(icon3)
        self.Set_btn.setIconSize(QtCore.QSize(40, 40))
        self.Set_btn.setCheckable(True)
        self.Set_btn.setObjectName("Set_btn")
        self.Interactive_widget.addWidget(self.DB_tab)
        self.Cfg_tab = QtWidgets.QWidget()
        self.Cfg_tab.setObjectName("Cfg_tab")
        self.Cfg_indicator = QtWidgets.QFrame(self.Cfg_tab)
        self.Cfg_indicator.setGeometry(QtCore.QRect(90, 10, 51, 3))
        self.Cfg_indicator.setStyleSheet("background-color:rgb(129, 192, 190);")
        self.Cfg_indicator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Cfg_indicator.setLineWidth(0)
        self.Cfg_indicator.setMidLineWidth(0)
        self.Cfg_indicator.setFrameShape(QtWidgets.QFrame.HLine)
        self.Cfg_indicator.setObjectName("Cfg_indicator")
        self.Port_label = QtWidgets.QLabel(self.Cfg_tab)
        self.Port_label.setGeometry(QtCore.QRect(20, 73, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Port_label.setFont(font)
        self.Port_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Port_label.setWordWrap(False)
        self.Port_label.setObjectName("Port_label")
        self.Port_sel = QtWidgets.QComboBox(self.Cfg_tab)
        self.Port_sel.setGeometry(QtCore.QRect(250, 73, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Port_sel.setFont(font)
        self.Port_sel.setStyleSheet("")
        self.Port_sel.setCurrentText("")
        self.Port_sel.setPlaceholderText("")
        self.Port_sel.setObjectName("Port_sel")
        self.Baudrate_label = QtWidgets.QLabel(self.Cfg_tab)
        self.Baudrate_label.setGeometry(QtCore.QRect(20, 125, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Baudrate_label.setFont(font)
        self.Baudrate_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Baudrate_label.setObjectName("Baudrate_label")
        self.Baudrate_sel = QtWidgets.QComboBox(self.Cfg_tab)
        self.Baudrate_sel.setGeometry(QtCore.QRect(250, 125, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Baudrate_sel.setFont(font)
        self.Baudrate_sel.setStyleSheet("#Port_sel {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#Port_sel:on {\n"
"    border: 2px solid rgb(0, 170, 127);\n"
"}\n"
"\n"
"#Port_sel QListView {\n"
"    selection-background-color:rgb(129, 192, 190);\n"
"}")
        self.Baudrate_sel.setObjectName("Baudrate_sel")
        self.Baudrate_sel.addItem("")
        self.Baudrate_sel.addItem("")
        self.Baudrate_sel.addItem("")
        self.Baudrate_sel.addItem("")
        self.Baudrate_sel.addItem("")
        self.Commu_cfg = QtWidgets.QLabel(self.Cfg_tab)
        self.Commu_cfg.setGeometry(QtCore.QRect(120, 35, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Commu_cfg.setFont(font)
        self.Commu_cfg.setAlignment(QtCore.Qt.AlignCenter)
        self.Commu_cfg.setObjectName("Commu_cfg")
        self.Cam_cfg = QtWidgets.QLabel(self.Cfg_tab)
        self.Cam_cfg.setGeometry(QtCore.QRect(120, 240, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Cam_cfg.setFont(font)
        self.Cam_cfg.setAlignment(QtCore.Qt.AlignCenter)
        self.Cam_cfg.setObjectName("Cam_cfg")
        self.Cam_label = QtWidgets.QLabel(self.Cfg_tab)
        self.Cam_label.setGeometry(QtCore.QRect(20, 280, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Cam_label.setFont(font)
        self.Cam_label.setObjectName("Cam_label")
        self.Cam_sel = QtWidgets.QComboBox(self.Cfg_tab)
        self.Cam_sel.setGeometry(QtCore.QRect(250, 280, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Cam_sel.setFont(font)
        self.Cam_sel.setObjectName("Cam_sel")
        self.Image_cfg = QtWidgets.QLabel(self.Cfg_tab)
        self.Image_cfg.setGeometry(QtCore.QRect(120, 400, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Image_cfg.setFont(font)
        self.Image_cfg.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_cfg.setObjectName("Image_cfg")
        self.HL_value = QtWidgets.QSlider(self.Cfg_tab)
        self.HL_value.setGeometry(QtCore.QRect(139, 440, 201, 22))
        self.HL_value.setMouseTracking(False)
        self.HL_value.setMinimum(0)
        self.HL_value.setMaximum(179)
        self.HL_value.setProperty("value", 90)
        self.HL_value.setOrientation(QtCore.Qt.Horizontal)
        self.HL_value.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.HL_value.setTickInterval(0)
        self.HL_value.setObjectName("HL_value")
        self.SL_value = QtWidgets.QSlider(self.Cfg_tab)
        self.SL_value.setGeometry(QtCore.QRect(139, 480, 201, 22))
        self.SL_value.setMaximum(255)
        self.SL_value.setOrientation(QtCore.Qt.Horizontal)
        self.SL_value.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SL_value.setObjectName("SL_value")
        self.VL_value = QtWidgets.QSlider(self.Cfg_tab)
        self.VL_value.setGeometry(QtCore.QRect(139, 520, 201, 22))
        self.VL_value.setMaximum(255)
        self.VL_value.setOrientation(QtCore.Qt.Horizontal)
        self.VL_value.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.VL_value.setObjectName("VL_value")
        self.HL_label = QtWidgets.QLabel(self.Cfg_tab)
        self.HL_label.setGeometry(QtCore.QRect(20, 440, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.HL_label.setFont(font)
        self.HL_label.setWordWrap(True)
        self.HL_label.setObjectName("HL_label")
        self.SL_label = QtWidgets.QLabel(self.Cfg_tab)
        self.SL_label.setGeometry(QtCore.QRect(20, 480, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.SL_label.setFont(font)
        self.SL_label.setObjectName("SL_label")
        self.VL_Label = QtWidgets.QLabel(self.Cfg_tab)
        self.VL_Label.setGeometry(QtCore.QRect(20, 520, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.VL_Label.setFont(font)
        self.VL_Label.setObjectName("VL_Label")
        self.VH_value = QtWidgets.QSlider(self.Cfg_tab)
        self.VH_value.setGeometry(QtCore.QRect(140, 650, 201, 22))
        self.VH_value.setMaximum(255)
        self.VH_value.setProperty("value", 255)
        self.VH_value.setOrientation(QtCore.Qt.Horizontal)
        self.VH_value.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.VH_value.setObjectName("VH_value")
        self.SH_label = QtWidgets.QLabel(self.Cfg_tab)
        self.SH_label.setGeometry(QtCore.QRect(21, 610, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.SH_label.setFont(font)
        self.SH_label.setObjectName("SH_label")
        self.HH_label = QtWidgets.QLabel(self.Cfg_tab)
        self.HH_label.setGeometry(QtCore.QRect(21, 570, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.HH_label.setFont(font)
        self.HH_label.setWordWrap(True)
        self.HH_label.setObjectName("HH_label")
        self.VH_label = QtWidgets.QLabel(self.Cfg_tab)
        self.VH_label.setGeometry(QtCore.QRect(21, 650, 111, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.VH_label.setFont(font)
        self.VH_label.setObjectName("VH_label")
        self.HH_value = QtWidgets.QSlider(self.Cfg_tab)
        self.HH_value.setGeometry(QtCore.QRect(140, 570, 201, 22))
        self.HH_value.setMinimum(0)
        self.HH_value.setMaximum(179)
        self.HH_value.setProperty("value", 130)
        self.HH_value.setOrientation(QtCore.Qt.Horizontal)
        self.HH_value.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.HH_value.setTickInterval(0)
        self.HH_value.setObjectName("HH_value")
        self.SH_value = QtWidgets.QSlider(self.Cfg_tab)
        self.SH_value.setGeometry(QtCore.QRect(140, 610, 201, 22))
        self.SH_value.setMaximum(255)
        self.SH_value.setProperty("value", 255)
        self.SH_value.setOrientation(QtCore.Qt.Horizontal)
        self.SH_value.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SH_value.setObjectName("SH_value")
        self.Others_cfg = QtWidgets.QLabel(self.Cfg_tab)
        self.Others_cfg.setGeometry(QtCore.QRect(120, 690, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Others_cfg.setFont(font)
        self.Others_cfg.setAlignment(QtCore.Qt.AlignCenter)
        self.Others_cfg.setObjectName("Others_cfg")
        self.Show_checkbox = QtWidgets.QCheckBox(self.Cfg_tab)
        self.Show_checkbox.setGeometry(QtCore.QRect(20, 720, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Show_checkbox.setFont(font)
        self.Show_checkbox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Show_checkbox.setChecked(True)
        self.Show_checkbox.setObjectName("Show_checkbox")
        self.HL_num = QtWidgets.QSpinBox(self.Cfg_tab)
        self.HL_num.setGeometry(QtCore.QRect(351, 441, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.HL_num.setFont(font)
        self.HL_num.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_num.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.HL_num.setMaximum(179)
        self.HL_num.setProperty("value", 90)
        self.HL_num.setObjectName("HL_num")
        self.SL_num = QtWidgets.QSpinBox(self.Cfg_tab)
        self.SL_num.setGeometry(QtCore.QRect(350, 480, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.SL_num.setFont(font)
        self.SL_num.setAlignment(QtCore.Qt.AlignCenter)
        self.SL_num.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SL_num.setMaximum(255)
        self.SL_num.setObjectName("SL_num")
        self.VL_num = QtWidgets.QSpinBox(self.Cfg_tab)
        self.VL_num.setGeometry(QtCore.QRect(350, 520, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.VL_num.setFont(font)
        self.VL_num.setAlignment(QtCore.Qt.AlignCenter)
        self.VL_num.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.VL_num.setMaximum(255)
        self.VL_num.setObjectName("VL_num")
        self.HH_num = QtWidgets.QSpinBox(self.Cfg_tab)
        self.HH_num.setGeometry(QtCore.QRect(350, 570, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.HH_num.setFont(font)
        self.HH_num.setAlignment(QtCore.Qt.AlignCenter)
        self.HH_num.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.HH_num.setMaximum(179)
        self.HH_num.setProperty("value", 130)
        self.HH_num.setObjectName("HH_num")
        self.SH_num = QtWidgets.QSpinBox(self.Cfg_tab)
        self.SH_num.setGeometry(QtCore.QRect(350, 610, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.SH_num.setFont(font)
        self.SH_num.setAlignment(QtCore.Qt.AlignCenter)
        self.SH_num.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.SH_num.setMaximum(255)
        self.SH_num.setProperty("value", 255)
        self.SH_num.setObjectName("SH_num")
        self.VH_num = QtWidgets.QSpinBox(self.Cfg_tab)
        self.VH_num.setGeometry(QtCore.QRect(350, 650, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.VH_num.setFont(font)
        self.VH_num.setAlignment(QtCore.Qt.AlignCenter)
        self.VH_num.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.VH_num.setMaximum(255)
        self.VH_num.setProperty("value", 255)
        self.VH_num.setObjectName("VH_num")
        self.Port_btn = QtWidgets.QPushButton(self.Cfg_tab)
        self.Port_btn.setGeometry(QtCore.QRect(130, 179, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Port_btn.setFont(font)
        self.Port_btn.setCheckable(True)
        self.Port_btn.setObjectName("Port_btn")
        self.Cam_btn = QtWidgets.QPushButton(self.Cfg_tab)
        self.Cam_btn.setGeometry(QtCore.QRect(130, 330, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Cam_btn.setFont(font)
        self.Cam_btn.setCheckable(True)
        self.Cam_btn.setObjectName("Cam_btn")
        self.Interactive_widget.addWidget(self.Cfg_tab)
        self.Info_tab = QtWidgets.QWidget()
        self.Info_tab.setObjectName("Info_tab")
        self.Info_indicator = QtWidgets.QFrame(self.Info_tab)
        self.Info_indicator.setGeometry(QtCore.QRect(160, 10, 51, 3))
        self.Info_indicator.setStyleSheet("background-color:rgb(129, 192, 190);")
        self.Info_indicator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Info_indicator.setLineWidth(0)
        self.Info_indicator.setMidLineWidth(0)
        self.Info_indicator.setFrameShape(QtWidgets.QFrame.HLine)
        self.Info_indicator.setObjectName("Info_indicator")
        self.label_2 = QtWidgets.QLabel(self.Info_tab)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 100, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\pics/HCMUTE.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Info_tab)
        self.label_3.setGeometry(QtCore.QRect(260, 60, 100, 100))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\pics/CLC.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.Project_name = QtWidgets.QLabel(self.Info_tab)
        self.Project_name.setGeometry(QtCore.QRect(30, 220, 341, 241))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.Project_name.setFont(font)
        self.Project_name.setScaledContents(True)
        self.Project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Project_name.setWordWrap(True)
        self.Project_name.setObjectName("Project_name")
        self.Project_name_2 = QtWidgets.QLabel(self.Info_tab)
        self.Project_name_2.setGeometry(QtCore.QRect(70, 670, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.Project_name_2.setFont(font)
        self.Project_name_2.setScaledContents(True)
        self.Project_name_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Project_name_2.setWordWrap(True)
        self.Project_name_2.setObjectName("Project_name_2")
        self.Project_name_3 = QtWidgets.QLabel(self.Info_tab)
        self.Project_name_3.setGeometry(QtCore.QRect(70, 500, 151, 111))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Project_name_3.setFont(font)
        self.Project_name_3.setScaledContents(True)
        self.Project_name_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Project_name_3.setWordWrap(True)
        self.Project_name_3.setObjectName("Project_name_3")
        self.Project_name_4 = QtWidgets.QLabel(self.Info_tab)
        self.Project_name_4.setGeometry(QtCore.QRect(230, 500, 91, 111))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        self.Project_name_4.setFont(font)
        self.Project_name_4.setScaledContents(True)
        self.Project_name_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Project_name_4.setWordWrap(True)
        self.Project_name_4.setObjectName("Project_name_4")
        self.Interactive_widget.addWidget(self.Info_tab)
        self.Camera_widget = QtWidgets.QWidget(self.centralwidget)
        self.Camera_widget.setGeometry(QtCore.QRect(440, 20, 841, 641))
        self.Camera_widget.setMinimumSize(QtCore.QSize(640, 480))
        self.Camera_widget.setStyleSheet("QWidget#Camera_widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"}")
        self.Camera_widget.setObjectName("Camera_widget")
        self.Camera_frame = QtWidgets.QLabel(self.Camera_widget)
        self.Camera_frame.setGeometry(QtCore.QRect(20, 20, 800, 600))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(22)
        self.Camera_frame.setFont(font)
        self.Camera_frame.setScaledContents(True)
        self.Camera_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.Camera_frame.setObjectName("Camera_frame")
        self.Output_widget = QtWidgets.QWidget(self.centralwidget)
        self.Output_widget.setGeometry(QtCore.QRect(440, 680, 841, 171))
        self.Output_widget.setStyleSheet("QWidget#Output_widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"QWidget#Output_bar{\n"
"    background-color: rgb(129, 192, 190);\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"QPlainTextEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.Output_widget.setObjectName("Output_widget")
        self.Output = QtWidgets.QPlainTextEdit(self.Output_widget)
        self.Output.setGeometry(QtCore.QRect(20, 80, 801, 71))
        self.Output.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.Output.setFont(font)
        self.Output.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Output.setStyleSheet("")
        self.Output.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Output.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Output.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.Output.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Output.setTabChangesFocus(True)
        self.Output.setReadOnly(True)
        self.Output.setTabStopDistance(8.0)
        self.Output.setMaximumBlockCount(7)
        self.Output.setBackgroundVisible(False)
        self.Output.setCenterOnScroll(False)
        self.Output.setObjectName("Output")
        self.Output_bar = QtWidgets.QWidget(self.Output_widget)
        self.Output_bar.setGeometry(QtCore.QRect(0, 0, 841, 61))
        self.Output_bar.setStyleSheet("")
        self.Output_bar.setObjectName("Output_bar")
        self.Output_label = QtWidgets.QLabel(self.Output_bar)
        self.Output_label.setGeometry(QtCore.QRect(720, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.Output_label.setFont(font)
        self.Output_label.setStyleSheet("background-color: rgb(129, 192, 190);")
        self.Output_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Output_label.setObjectName("Output_label")
        self.Tab_widget = QtWidgets.QWidget(self.centralwidget)
        self.Tab_widget.setGeometry(QtCore.QRect(20, 20, 401, 61))
        self.Tab_widget.setStyleSheet("QPushButton {\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"QWidget{\n"
"    background-color: rgb(129, 192, 190);\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"")
        self.Tab_widget.setObjectName("Tab_widget")
        self.DB_btn = QtWidgets.QPushButton(self.Tab_widget)
        self.DB_btn.setGeometry(QtCore.QRect(10, 10, 71, 51))
        self.DB_btn.setStyleSheet("")
        self.DB_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\icons/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DB_btn.setIcon(icon4)
        self.DB_btn.setIconSize(QtCore.QSize(35, 35))
        self.DB_btn.setObjectName("DB_btn")
        self.Cfg_btn = QtWidgets.QPushButton(self.Tab_widget)
        self.Cfg_btn.setGeometry(QtCore.QRect(80, 10, 71, 51))
        self.Cfg_btn.setStyleSheet("")
        self.Cfg_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Cfg_btn.setIcon(icon5)
        self.Cfg_btn.setIconSize(QtCore.QSize(35, 35))
        self.Cfg_btn.setObjectName("Cfg_btn")
        self.Info_btn = QtWidgets.QPushButton(self.Tab_widget)
        self.Info_btn.setGeometry(QtCore.QRect(150, 10, 71, 51))
        self.Info_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\icons/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Info_btn.setIcon(icon6)
        self.Info_btn.setIconSize(QtCore.QSize(35, 35))
        self.Info_btn.setObjectName("Info_btn")
        self.Tab_name = QtWidgets.QStackedWidget(self.Tab_widget)
        self.Tab_name.setGeometry(QtCore.QRect(220, 10, 181, 41))
        self.Tab_name.setObjectName("Tab_name")
        self.DB_name = QtWidgets.QWidget()
        self.DB_name.setObjectName("DB_name")
        self.DB_label = QtWidgets.QLabel(self.DB_name)
        self.DB_label.setGeometry(QtCore.QRect(20, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.DB_label.setFont(font)
        self.DB_label.setAlignment(QtCore.Qt.AlignCenter)
        self.DB_label.setObjectName("DB_label")
        self.Tab_name.addWidget(self.DB_name)
        self.Cfg_name = QtWidgets.QWidget()
        self.Cfg_name.setObjectName("Cfg_name")
        self.Cfg_label = QtWidgets.QLabel(self.Cfg_name)
        self.Cfg_label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Cfg_label.setFont(font)
        self.Cfg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Cfg_label.setObjectName("Cfg_label")
        self.Tab_name.addWidget(self.Cfg_name)
        self.Info_name = QtWidgets.QWidget()
        self.Info_name.setObjectName("Info_name")
        self.Info_label = QtWidgets.QLabel(self.Info_name)
        self.Info_label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Info_label.setFont(font)
        self.Info_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Info_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Info_label.setObjectName("Info_label")
        self.Tab_name.addWidget(self.Info_name)
        self.Expandable_widget = QtWidgets.QWidget(self.centralwidget)
        self.Expandable_widget.setGeometry(QtCore.QRect(1300, 20, 381, 831))
        self.Expandable_widget.setStyleSheet("QWidget#Expandable_widget {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px;\n"
"}\n"
"QWidget#Expandable_bar{\n"
"    background-color: rgb(129, 192, 190);\n"
"    border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLabel#Contour_frame {\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"}\n"
"\n"
"QLabel#minCircle_frame {\n"
"    border: 2px solid rgb(129, 192, 190);\n"
"}")
        self.Expandable_widget.setObjectName("Expandable_widget")
        self.Expandable_bar = QtWidgets.QWidget(self.Expandable_widget)
        self.Expandable_bar.setGeometry(QtCore.QRect(0, 0, 381, 61))
        self.Expandable_bar.setObjectName("Expandable_bar")
        self.Expandable_label = QtWidgets.QLabel(self.Expandable_bar)
        self.Expandable_label.setGeometry(QtCore.QRect(250, 19, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.Expandable_label.setFont(font)
        self.Expandable_label.setStyleSheet("background-color: rgb(129, 192, 190);")
        self.Expandable_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Expandable_label.setObjectName("Expandable_label")
        self.Contour_frame = QtWidgets.QLabel(self.Expandable_widget)
        self.Contour_frame.setGeometry(QtCore.QRect(40, 130, 300, 300))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.Contour_frame.setFont(font)
        self.Contour_frame.setScaledContents(True)
        self.Contour_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.Contour_frame.setWordWrap(True)
        self.Contour_frame.setObjectName("Contour_frame")
        self.minCircle_frame = QtWidgets.QLabel(self.Expandable_widget)
        self.minCircle_frame.setGeometry(QtCore.QRect(40, 500, 300, 300))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(18)
        self.minCircle_frame.setFont(font)
        self.minCircle_frame.setScaledContents(True)
        self.minCircle_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.minCircle_frame.setWordWrap(True)
        self.minCircle_frame.setObjectName("minCircle_frame")
        self.Contour_label = QtWidgets.QLabel(self.Expandable_widget)
        self.Contour_label.setGeometry(QtCore.QRect(70, 80, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Contour_label.setFont(font)
        self.Contour_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Contour_label.setObjectName("Contour_label")
        self.minCircle_label = QtWidgets.QLabel(self.Expandable_widget)
        self.minCircle_label.setGeometry(QtCore.QRect(30, 450, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.minCircle_label.setFont(font)
        self.minCircle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.minCircle_label.setObjectName("minCircle_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Interactive_widget.setCurrentIndex(0)
        self.Tab_name.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.DB_btn, self.Cfg_btn)
        MainWindow.setTabOrder(self.Cfg_btn, self.Info_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TTL Classification"))
        self.Result_frame.setText(_translate("MainWindow", "Result"))
        self.Result_label.setText(_translate("MainWindow", "Result"))
        self.Total_label.setText(_translate("MainWindow", "Total Classified:"))
        self.Passed_label.setText(_translate("MainWindow", "Passed:"))
        self.Failed_label.setText(_translate("MainWindow", "Failed:"))
        self.Start_btn.setText(_translate("MainWindow", "Start"))
        self.Stop_btn.setText(_translate("MainWindow", "Stop"))
        self.Set_btn.setText(_translate("MainWindow", "Set Value"))
        self.Port_label.setText(_translate("MainWindow", "Select COM Port"))
        self.Baudrate_label.setText(_translate("MainWindow", "Select Baudrate"))
        self.Baudrate_sel.setCurrentText(_translate("MainWindow", "9600"))
        self.Baudrate_sel.setItemText(0, _translate("MainWindow", "9600"))
        self.Baudrate_sel.setItemText(1, _translate("MainWindow", "19200"))
        self.Baudrate_sel.setItemText(2, _translate("MainWindow", "38400"))
        self.Baudrate_sel.setItemText(3, _translate("MainWindow", "51200"))
        self.Baudrate_sel.setItemText(4, _translate("MainWindow", "115200"))
        self.Commu_cfg.setText(_translate("MainWindow", "Communication"))
        self.Cam_cfg.setText(_translate("MainWindow", "Camera"))
        self.Cam_label.setText(_translate("MainWindow", "Select Camera"))
        self.Image_cfg.setText(_translate("MainWindow", "Image Process"))
        self.HL_label.setText(_translate("MainWindow", "H lower value"))
        self.SL_label.setText(_translate("MainWindow", "S lower value"))
        self.VL_Label.setText(_translate("MainWindow", "V lower value"))
        self.SH_label.setText(_translate("MainWindow", "S upper value"))
        self.HH_label.setText(_translate("MainWindow", "H upper value"))
        self.VH_label.setText(_translate("MainWindow", "V upper value"))
        self.Others_cfg.setText(_translate("MainWindow", "Others"))
        self.Show_checkbox.setText(_translate("MainWindow", "Show expand tab of image process      "))
        self.Port_btn.setText(_translate("MainWindow", "Connect Port"))
        self.Cam_btn.setText(_translate("MainWindow", "Connect Camera"))
        self.Project_name.setText(_translate("MainWindow", "PROJECTS OF MECHATRONICS SYSTEM\n"
"DESIGN AND IMPLEMENTATION OF BEARING COVER DEFECTS DETECTING USING \n"
"IMAGE PROCESSING"))
        self.Project_name_2.setText(_translate("MainWindow", "Advisor: ME. NGUYEN MINH TRIET"))
        self.Project_name_3.setText(_translate("MainWindow", "Trần Việt Thắng An Thanh Tùng Hoàng Phi Long"))
        self.Project_name_4.setText(_translate("MainWindow", "18146062 18142073 18146040"))
        self.Camera_frame.setText(_translate("MainWindow", "Camera"))
        self.Output.setPlainText(_translate("MainWindow", "Bearing Seals Classification"))
        self.Output_label.setText(_translate("MainWindow", "Output"))
        self.DB_label.setText(_translate("MainWindow", "Dashboard"))
        self.Cfg_label.setText(_translate("MainWindow", "Config"))
        self.Info_label.setText(_translate("MainWindow", "Info"))
        self.Expandable_label.setText(_translate("MainWindow", "Process"))
        self.Contour_frame.setText(_translate("MainWindow", "Contour Detect Process"))
        self.minCircle_frame.setText(_translate("MainWindow", "Minimum Enclosing Circle Process"))
        self.Contour_label.setText(_translate("MainWindow", "Contour Detect Process"))
        self.minCircle_label.setText(_translate("MainWindow", "Minimum Enclosing Circle Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
